
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Family
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        HadasBotones = new javax.swing.ButtonGroup();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rd_lamias = new javax.swing.JRadioButton();
        rd_silfides = new javax.swing.JRadioButton();
        rb_hamadriades = new javax.swing.JRadioButton();
        rb_salamandras = new javax.swing.JRadioButton();
        tf_nombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sp_altura = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        tf_edad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lamias_alas = new javax.swing.JSpinner();
        lamias_branquias = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        silfides_alas = new javax.swing.JSpinner();
        salamandras_alas = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        rd_lamias1 = new javax.swing.JRadioButton();
        rd_silfides1 = new javax.swing.JRadioButton();
        rb_hamadriades1 = new javax.swing.JRadioButton();
        rb_salamandras1 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        tf_nombres1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        sp_altura1 = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        tf_edad1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        guardarcomo = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        about = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("Agregar");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setText("¿Que tipo de Hada?");

        HadasBotones.add(rd_lamias);
        rd_lamias.setText("Lamias");
        rd_lamias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rd_lamiasItemStateChanged(evt);
            }
        });
        rd_lamias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rd_lamiasMouseClicked(evt);
            }
        });

        HadasBotones.add(rd_silfides);
        rd_silfides.setText("Silfides");
        rd_silfides.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rd_silfidesMouseClicked(evt);
            }
        });

        HadasBotones.add(rb_hamadriades);
        rb_hamadriades.setText("Hamadriades");
        rb_hamadriades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_hamadriadesMouseClicked(evt);
            }
        });
        rb_hamadriades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_hamadriadesActionPerformed(evt);
            }
        });

        HadasBotones.add(rb_salamandras);
        rb_salamandras.setText("Salamandras");
        rb_salamandras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_salamandrasMouseClicked(evt);
            }
        });

        jLabel3.setText("Nombre:");

        jLabel4.setText("Altura:");

        sp_altura.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));

        jLabel5.setText("Edad:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("Lamias");

        jLabel8.setText("Aleta:");

        jLabel9.setText("Branquias");

        lamias_alas.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 5.0d, 1.0d));

        lamias_branquias.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 8.0d, 1.0d));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("Silfides");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setText("Salamandras");

        jLabel13.setText("Alas");

        silfides_alas.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 6.0d, 1.0d));

        salamandras_alas.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 16.0d, 1.0d));

        jLabel10.setText("Alas");

        jButton5.setText("Guardar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rd_silfides)
                                .addComponent(rd_lamias))
                            .addComponent(rb_hamadriades)
                            .addComponent(rb_salamandras)
                            .addComponent(jLabel7))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(8, 8, 8)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nombres)
                                    .addComponent(sp_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_edad, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(94, 94, 94)
                                        .addComponent(jLabel12))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(silfides_alas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(salamandras_alas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(331, 331, 331))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(28, 28, 28)
                        .addComponent(lamias_alas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lamias_branquias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(rd_lamias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rd_silfides))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_hamadriades)
                    .addComponent(jLabel4)
                    .addComponent(sp_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_salamandras)
                    .addComponent(jLabel5)
                    .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lamias_alas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(silfides_alas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salamandras_alas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lamias_branquias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Agregar", jPanel5);

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel17.setText("Agregar");

        HadasBotones.add(rd_lamias1);
        rd_lamias1.setText("Lamias");
        rd_lamias1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rd_lamias1ItemStateChanged(evt);
            }
        });
        rd_lamias1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rd_lamias1MouseClicked(evt);
            }
        });

        HadasBotones.add(rd_silfides1);
        rd_silfides1.setText("Silfides");
        rd_silfides1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rd_silfides1MouseClicked(evt);
            }
        });

        HadasBotones.add(rb_hamadriades1);
        rb_hamadriades1.setText("Hamadriades");
        rb_hamadriades1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_hamadriades1MouseClicked(evt);
            }
        });
        rb_hamadriades1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_hamadriades1ActionPerformed(evt);
            }
        });

        HadasBotones.add(rb_salamandras1);
        rb_salamandras1.setText("Salamandras");
        rb_salamandras1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_salamandras1MouseClicked(evt);
            }
        });

        jButton6.setText("Guardar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel22.setText("¿Que tipo de Hada?");

        jLabel23.setText("Nombre:");

        jLabel24.setText("Altura:");

        sp_altura1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));

        jLabel25.setText("Edad:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_hamadriades1)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rd_silfides1)
                        .addComponent(rd_lamias1))
                    .addComponent(rb_salamandras1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel24)
                        .addComponent(jLabel23))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nombres1)
                    .addComponent(sp_altura1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(246, 246, 246))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)
                        .addGap(21, 21, 21)
                        .addComponent(rd_lamias1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rd_silfides1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_nombres1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(sp_altura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rb_hamadriades1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(tf_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rb_salamandras1))
                .addGap(109, 109, 109)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Modificar", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Eliminar", jPanel7);

        jMenu1.setText("Menu");

        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        jMenu1.add(abrir);

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jMenu1.add(guardar);

        guardarcomo.setText("Guardar Como");
        guardarcomo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarcomoActionPerformed(evt);
            }
        });
        jMenu1.add(guardarcomo);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu1.add(salir);

        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jMenu1.add(about);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        if (rd_lamias.isSelected()) {
            hadas hl = new lamias(((Number) lamias_alas.getValue()).floatValue(), ((Number) lamias_branquias.getValue()).doubleValue(), tf_nombres.getText(), tf_edad.getText(), ((Number) sp_altura.getValue()).doubleValue());

            ah.setPersona(hl);
            JOptionPane.showMessageDialog(this, "Se ha creado");
        }
        if (rd_silfides.isSelected()) {
            hadas hs = new silfides(((Number) silfides_alas.getValue()).doubleValue(), tf_nombres.getText(), tf_edad.getText(), ((Number) sp_altura.getValue()).doubleValue());
            ah.setPersona(hs);
            JOptionPane.showMessageDialog(this, "Se ha creado");
        }
        if (rb_hamadriades.isSelected()) {
            hadas hh = new hamadriades(tf_nombres.getText(), tf_edad.getText(), ((Number) sp_altura.getValue()).doubleValue());
            ah.setPersona(hh);
            JOptionPane.showMessageDialog(this, "Se ha creado");
        }
        if (rb_salamandras.isSelected()) {
            hadas hs = new salamandras(((Number) salamandras_alas.getValue()).doubleValue(), tf_nombres.getText(), tf_edad.getText(), ((Number) sp_altura.getValue()).doubleValue());
            ah.setPersona(hs);
            JOptionPane.showMessageDialog(this, "Se ha creado");
        }
///////////

    }//GEN-LAST:event_jButton5MouseClicked

    private void rb_salamandrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_salamandrasMouseClicked

        if (rb_salamandras.isSelected()) {
            lamias_alas.setEnabled(false);
            lamias_branquias.setEnabled(false);
            salamandras_alas.setEnabled(true);
            silfides_alas.setEnabled(false);
        }
    }//GEN-LAST:event_rb_salamandrasMouseClicked

    private void rb_hamadriadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_hamadriadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_hamadriadesActionPerformed

    private void rb_hamadriadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_hamadriadesMouseClicked
        if (rb_hamadriades.isSelected()) {
            lamias_alas.setEnabled(false);
            lamias_branquias.setEnabled(false);
            salamandras_alas.setEnabled(false);
            silfides_alas.setEnabled(false);
        }
    }//GEN-LAST:event_rb_hamadriadesMouseClicked

    private void rd_silfidesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rd_silfidesMouseClicked
        if (rd_silfides.isSelected()) {
            lamias_alas.setEnabled(false);
            lamias_branquias.setEnabled(false);
            silfides_alas.setEnabled(true);
            salamandras_alas.setEnabled(false);
        }
    }//GEN-LAST:event_rd_silfidesMouseClicked

    private void rd_lamiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rd_lamiasMouseClicked
        if (rd_lamias.isSelected()) {
            silfides_alas.setEnabled(false);
            salamandras_alas.setEnabled(false);
            lamias_alas.setEnabled(true);
            lamias_branquias.setEnabled(true);
        }

    }//GEN-LAST:event_rd_lamiasMouseClicked

    private void rd_lamiasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rd_lamiasItemStateChanged

    }//GEN-LAST:event_rd_lamiasItemStateChanged

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed

    private void guardarcomoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarcomoActionPerformed

        ///guardar como --------------------
        JFileChooser jfc = new JFileChooser();
        int seleccion = jfc.showSaveDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {

                fichero = jfc.getSelectedFile();
                FileOutputStream fw = null;
                ObjectOutputStream bw = null;
                try {
                    fw = new FileOutputStream(fichero + ".cbm");
                    bw = new ObjectOutputStream(fw);
                    for (hadas t : ah.listahadas) {
                        bw.writeObject(t);
                    }
                    bw.flush();
                } catch (Exception e) {
                } finally {
                    try {
                        bw.close();
                        fw.close();
                    } catch (Exception e) {
                    }
                }
                //fw = new FileWriter(fichero + ".cbm");
                //bw = new BufferedWriter(fw);
                bw.flush();
                JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente");
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    // bw.close();
                    //fw.close();
                } catch (Exception e) {
                }
            }
        }
        guardarcomo.setEnabled(false);
    }//GEN-LAST:event_guardarcomoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        JOptionPane.showMessageDialog(this, "Juego de Hadas \n" + "Este juego se trata de crear sus propias Hadas \n" + "y hacerlas pelear hasta que una de las 2 pierda");
    }//GEN-LAST:event_aboutActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed

        FileReader fr = null;
        BufferedReader br = null;

        try {
            JFileChooser jfc = new JFileChooser();
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de Texto", "cbm");
            FileNameExtensionFilter filtro2 = new FileNameExtensionFilter("Imagenes", "jpg", "png", "bmp");
            jfc.setFileFilter(filtro);
            jfc.addChoosableFileFilter(filtro2);
            int seleccion = jfc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = jfc.getSelectedFile();
                try {
                    ah.listahadas = new ArrayList();
                    hadas temp;
                    if (fichero.exists()) {
                        FileInputStream entrada = new FileInputStream(fichero);
                        ObjectInputStream objeto = new ObjectInputStream(entrada);
                        try {
                            while ((temp = (hadas) objeto.readObject()) != null) {
                                ah.listahadas.add(temp);
                            }
                        } catch (EOFException e) {
                            //encontro el final del archivo
                        }
                        objeto.close();
                        entrada.close();
                    }//fin if
                } catch (Exception e) {
                    e.printStackTrace();
                }

                fr = new FileReader(fichero);
                br = new BufferedReader(fr);
                String linea;

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            br.close();
            fr.close();
        } catch (Exception e) {
        }

        DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBox1.getModel();
        for (int i = 0; i < ah.listahadas.size(); i++) {
            if (model.getIndexOf(ah.listahadas.get(i).getNombre())
                    == -1) {
                model.addElement(ah.listahadas.get(i).getNombre());
            }

        }
    }//GEN-LAST:event_abrirActionPerformed

    private void rd_lamias1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rd_lamias1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_lamias1ItemStateChanged

    private void rd_lamias1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rd_lamias1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_lamias1MouseClicked

    private void rd_silfides1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rd_silfides1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_silfides1MouseClicked

    private void rb_hamadriades1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_hamadriades1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_hamadriades1MouseClicked

    private void rb_hamadriades1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_hamadriades1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_hamadriades1ActionPerformed

    private void rb_salamandras1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_salamandras1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_salamandras1MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        String nombre = (String) jComboBox1.getSelectedItem();
        for (int i = 0; i < ah.listahadas.size(); i++) {
            if (ah.listahadas.get(i).getNombre().equals(nombre)) {
                if (ah.listahadas.get(i).getTipo().equals("Lamias")) {
                    rd_lamias1.setSelected(true);

                    tf_nombres1.setText(ah.listahadas.get(i).getNombre());
                    tf_edad1.setText(ah.listahadas.get(i).getEdad());
                    sp_altura1.setValue(ah.listahadas.get(i).getAltura());

                }
                if (ah.listahadas.get(i).getTipo().equals("Salamandras")) {
                    rb_salamandras1.setSelected(true);

                    tf_nombres1.setText(ah.listahadas.get(i).getNombre());
                    tf_edad1.setText(ah.listahadas.get(i).getEdad());
                    sp_altura1.setValue(ah.listahadas.get(i).getAltura());
                }
                if (ah.listahadas.get(i).getTipo().equals("Hamadriades")) {
                    rb_hamadriades1.setSelected(true);

                    tf_nombres1.setText(ah.listahadas.get(i).getNombre());
                    tf_edad1.setText(ah.listahadas.get(i).getEdad());
                    sp_altura1.setValue(ah.listahadas.get(i).getAltura());
                }
                if (ah.listahadas.get(i).getTipo().equals("Silfides")) {
                    rd_silfides1.setSelected(true);

                    tf_nombres1.setText(ah.listahadas.get(i).getNombre());
                    tf_edad1.setText(ah.listahadas.get(i).getEdad());
                    sp_altura1.setValue(ah.listahadas.get(i).getAltura());
                }

            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup HadasBotones;
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem abrir;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JMenuItem guardarcomo;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JSpinner lamias_alas;
    private javax.swing.JSpinner lamias_branquias;
    private javax.swing.JRadioButton rb_hamadriades;
    private javax.swing.JRadioButton rb_hamadriades1;
    private javax.swing.JRadioButton rb_salamandras;
    private javax.swing.JRadioButton rb_salamandras1;
    private javax.swing.JRadioButton rd_lamias;
    private javax.swing.JRadioButton rd_lamias1;
    private javax.swing.JRadioButton rd_silfides;
    private javax.swing.JRadioButton rd_silfides1;
    private javax.swing.JSpinner salamandras_alas;
    private javax.swing.JMenuItem salir;
    private javax.swing.JSpinner silfides_alas;
    private javax.swing.JSpinner sp_altura;
    private javax.swing.JSpinner sp_altura1;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_edad1;
    private javax.swing.JTextField tf_nombres;
    private javax.swing.JTextField tf_nombres1;
    // End of variables declaration//GEN-END:variables
File fichero;
    administrarHadas ah = new administrarHadas();
}
